"""Migração Inicial

Revision ID: c7545688d697
Revises: 
Create Date: 2024-11-21 08:05:40.783097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7545688d697'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurantes',
    sa.Column('id_restaurante', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_restaurante')
    )
    op.create_table('pratos',
    sa.Column('id_pratos', sa.Integer(), nullable=False),
    sa.Column('id_restaurantes', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('preco', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.ForeignKeyConstraint(['id_restaurantes'], ['restaurantes.id_restaurante'], ),
    sa.PrimaryKeyConstraint('id_pratos')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pratos')
    op.drop_table('restaurantes')
    # ### end Alembic commands ###
